"""Update relationships: user_login -> user_dtls one-to-many, user_dtls -> qr_dtls one-to-many

Revision ID: adb00e8c6ac9
Revises: e7eddabf84ad
Create Date: 2025-10-03 20:58:22.218931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adb00e8c6ac9'
down_revision = 'e7eddabf84ad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('qr_dtls', sa.Column('user_dtls_id', sa.UUID(), nullable=True))
    
    # Data migration: Update existing QR codes to reference user_dtls.id instead of user_login.id
    # This assumes each user_login has exactly one user_dtls record
    op.execute("""
        UPDATE qr_dtls 
        SET user_dtls_id = user_dtls.id 
        FROM user_dtls 
        WHERE qr_dtls.user_id = user_dtls.user_id
    """)
    
    op.drop_constraint('qr_dtls_user_id_fkey', 'qr_dtls', type_='foreignkey')
    op.create_foreign_key(None, 'qr_dtls', 'user_dtls', ['user_dtls_id'], ['id'])
    op.drop_column('qr_dtls', 'user_id')
    op.drop_constraint('user_dtls_user_id_key', 'user_dtls', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('user_dtls_user_id_key', 'user_dtls', ['user_id'])
    op.add_column('qr_dtls', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'qr_dtls', type_='foreignkey')
    op.create_foreign_key('qr_dtls_user_id_fkey', 'qr_dtls', 'user_login', ['user_id'], ['id'])
    op.drop_column('qr_dtls', 'user_dtls_id')
    # ### end Alembic commands ###

