"""Add role column to user_login

Revision ID: eb6ec02c1b95
Revises: adb00e8c6ac9
Create Date: 2025-10-03 21:06:24.832249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6ec02c1b95'
down_revision = 'adb00e8c6ac9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_login', sa.Column('role', sa.Integer(), nullable=True))
    op.execute("UPDATE user_login SET role = 1 WHERE role IS NULL")
    op.alter_column('user_login', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_login', 'role')
    # ### end Alembic commands ###

